Affected Issue(s): https://www.notion.so/sid-indonesia/Improve-data-completeness-care-coverage-etc-by-adding-integration-with-Qontak-WhatsApp-API-to-sen-b6b404d36c264cb293d2a7a1a356006d
What this commit has achieved:
1. Fixed
```
org.postgresql.util.PSQLException: ERROR: cannot execute INSERT in a
read-only transaction
```
by removing hint `readOnly = true` in annotation `@Transactional`.
Because at the end of the scheduled task is upsert
`automated_message_stats`